#!/usr/bin/env bash
# Wire product repo to vendored demir-kit. Run from product repo root.
# Usage: KIT_ROOT=vendor/demir-kit ./vendor/demir-kit/tools/kit-setup.sh --repo owner/name
set -euo pipefail

REPO=""
KIT_ROOT="${KIT_ROOT:-vendor/demir-kit}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="$2"; shift 2 ;;
    --kit-root) KIT_ROOT="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

if [[ ! -f "$KIT_ROOT/VERSION" ]]; then
  echo "kit-setup: missing $KIT_ROOT/VERSION — clone full demir-kit to vendor/demir-kit"
  exit 1
fi

VERSION="$(tr -d '[:space:]' < "$KIT_ROOT/VERSION")"

if [[ -z "$REPO" ]] && command -v gh >/dev/null 2>&1; then
  REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)"
fi

if [[ -z "$REPO" ]]; then
  echo "kit-setup: pass --repo owner/name"
  exit 1
fi

mkdir -p docs/agent

if [[ ! -f docs/agent/workflow.md ]]; then
  cp "$KIT_ROOT/templates/project/docs/agent/workflow.md" docs/agent/workflow.md
fi

if [[ ! -f AGENTS.md ]]; then
  sed "s|vendor/demir-kit|$KIT_ROOT|g" "$KIT_ROOT/templates/project/AGENTS.md" > AGENTS.md
fi

if [[ -f .gitignore ]] && ! grep -q '.orchestration/' .gitignore 2>/dev/null; then
  cat "$KIT_ROOT/templates/project/.gitignore.append" >> .gitignore
fi

cat > kit.config.yaml <<EOF
# Generated by kit-setup.sh — edit factory.default_profile if needed
kit:
  root: $KIT_ROOT
  version: "$VERSION"
  protocol: "1"

tracker:
  provider: github
  repo: $REPO

orca:
  skills_required:
    - orchestration
    - orca-cli
  integration: references/orca-integration.md
  gate_contract: references/gate-contract.md
  orchestration_readme: orchestration/README.md

factory:
  default_profile: game-flutter
EOF

echo "kit-setup: wrote kit.config.yaml (kit $VERSION, repo $REPO)"
echo "Next: $KIT_ROOT/tools/kit-init.sh --repo $REPO"
